### ISSUE TITLE
Providing unexpected trait value type when evaluating semver causes TypeError

### ISSUE THREAD

**Issue by matthewelwell** [Flagsmith/flagsmith-engine#194]
To reproduce: 

 1. Given a segment that has a condition like `version SEMVER_GT 1.0.0` 
 2. Evaluate `get_identity_feature_states(...)` using an identity that has e.g. `version = 1.0` 

This will cause 

`TypeError: not expecting type '<class 'float'>'`

Note that this was picked up by our Edge API which is throwing a 500 error in this scenario currently.

**Comment by khvn26** [comment]
This actually was fixed in 4.1.0! Opened a PR to Edge API with a bump: https://github.com/Flagsmith/edge-api/pull/207
