### ISSUE TITLE
👕 Implement port of rules engine to Elixir, Rust & Golang and win 2 t-shirts

### ISSUE THREAD

**Issue by hroussel** [Flagsmith/flagsmith-engine#58]
**Overview**

As @dabeeeenster [discussed on the Axx Podcast](https://www.youtube.com/watch?v=JryShrvjo3o&t=2418s), one of the goals of Flagsmith is server-side SDK support. It would be great to get some community help! It's only 600 lines of Python and there will be a test harness #30 to make sure the implementation is correct. 

**How**

1. Pick one of the unsupported server-side languages: Elixir, Rust, Golang, Java, Javascript, PHP, Ruby. Explore the code for the engine on [Quod AI](https://bit.ly/3Gk9pLw).
2. Port the engine code from Python to the language in step 1.
3. Pass the test harness!

**Prizes**

Flagsmith & Quod AI are joining forces. The first PR that gets merged to main will win 2 free t-shirts!
![Tshirts](https://user-images.githubusercontent.com/994814/144956746-190c7a47-b16b-4185-ab54-7fefad5ce92a.jpg)

**Comment by matthewelwell** [comment]
Hey @hroussel, thanks for this! 

I'd just like to add that the functionality in the `django_transform` module does not need replicating in other languages. The functionality in this module allows us to convert our django entities into documents to store for our (currently beta) Edge API. For obvious reasons we wouldn't need that functionality translated to other languages.
